name: Discord Exporter and Summarizer

on:
  schedule:
    - cron: '0 8 * * *'  # Ejecuta todos los días a las 8 AM UTC

jobs:
  run-discord-exporter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'
      - name: Run Discord Exporter
        run: |
          dotnet run discord-exporter.cs
      - name: Summarize with OpenAI
        run: |
          export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          SUMMARY=$(curl -s -X POST https://api.openai.com/v1/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d '{
              "model": "text-davinci-003",
              "prompt": "Resumir este texto de Discord: $(cat output.txt)",
              "max_tokens": 150
            }' | jq -r '.choices[0].text')
          echo "$SUMMARY" > summary.txt
          curl -X POST -H 'Content-type: application/json' --data '{"text":"$(cat summary.txt)"}' ${{ secrets.SLACK_WEBHOOK_URL }}
